default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: delivery
  password: 21062013
  host: 127.0.0.1

development:
  <<: *default
  database: delivery_app

test:
  <<: *default
  database: delivery_app_test

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
